In [2]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import nflfastpy as nfl
import re

In [14]:
yearly_url = 'https://raw.githubusercontent.com/fantasydatapros/data/master/yearly/{year}.csv'
start_year = 2013
end_year = 2020 # As of 6/22/22, the repository above only contains yearly data up to and including the 2020 season. 

yearly_df = pd.DataFrame()
for year in range(start_year, end_year+1):
    year_df = pd.read_csv(yearly_url.format(year=year))
    year_df['Season'] = year
    col_name = year_df.columns.tolist()
    col_name.pop()
    col_name.insert(0, 'Season')
    year_df = year_df[col_name]
    yearly_df = pd.concat([yearly_df, year_df])
yearly_df.drop(columns=['Unnamed: 0'], inplace=True)
print(yearly_df.shape)
yearly_df.head()

(4927, 21)

,Season,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,...,PassingAtt,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost
0,2013,Jamaal Charles,KAN,RB,27.0,15.0,15.0,104.0,70.0,0.0,...,0.0,1287.0,12.0,259.0,693.0,7.0,378.00,0.0,4.0,2.0
1,2013,Peyton Manning,DEN,QB,37.0,16.0,16.0,0.0,0.0,5477.0,...,659.0,-31.0,1.0,32.0,0.0,0.0,409.98,10.0,11.0,6.0
2,2013,LeSean McCoy,PHI,RB,25.0,16.0,16.0,64.0,52.0,0.0,...,0.0,1607.0,9.0,314.0,539.0,2.0,330.60,0.0,1.0,1.0
3,2013,Matt Forte,CHI,RB,28.0,16.0,16.0,95.0,74.0,0.0,...,0.0,1339.0,9.0,289.0,594.0,3.0,335.30,0.0,2.0,2.0
4,2013,Marshawn Lynch,SEA,RB,27.0,16.0,16.0,44.0,36.0,0.0,...,0.0,1257.0,12.0,301.0,316.0,2.0,275.30,0.0,4.0,1.0

In [15]:
# Attach scraped 2021 yearly season data to yearly_df 

year_2021_df = pd.read_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/yearly_2021.csv')
year_2021_df['Season'] = 2021
year_2021_df = year_2021_df[col_name]

yearly_df = pd.concat([yearly_df, year_2021_df])
print(yearly_df.shape)
yearly_df.head()

(5598, 21)

,Season,Player,Tm,Pos,Age,G,GS,Tgt,Rec,PassingYds,...,PassingAtt,RushingYds,RushingTD,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost
0,2013,Jamaal Charles,KAN,RB,27.0,15.0,15.0,104.0,70.0,0.0,...,0.0,1287.0,12.0,259.0,693.0,7.0,378.00,0.0,4.0,2.0
1,2013,Peyton Manning,DEN,QB,37.0,16.0,16.0,0.0,0.0,5477.0,...,659.0,-31.0,1.0,32.0,0.0,0.0,409.98,10.0,11.0,6.0
2,2013,LeSean McCoy,PHI,RB,25.0,16.0,16.0,64.0,52.0,0.0,...,0.0,1607.0,9.0,314.0,539.0,2.0,330.60,0.0,1.0,1.0
3,2013,Matt Forte,CHI,RB,28.0,16.0,16.0,95.0,74.0,0.0,...,0.0,1339.0,9.0,289.0,594.0,3.0,335.30,0.0,2.0,2.0
4,2013,Marshawn Lynch,SEA,RB,27.0,16.0,16.0,44.0,36.0,0.0,...,0.0,1257.0,12.0,301.0,316.0,2.0,275.30,0.0,4.0,1.0

In [ ]:
# yearly_df.to_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/yearly_compiled_2013_2021.csv')

In [16]:
# Grab roster data from nflfastr

roster_url = 'https://raw.githubusercontent.com/nflverse/nflfastR-roster/master/data/seasons/roster_{year}.csv'
s_year = 2013
e_year = 2021
roster_df = pd.DataFrame()

for year in range(s_year, e_year+1):
     r_df = pd.read_csv(roster_url.format(year=year))
     r_df['Season'] = year
     col_name = r_df.columns.tolist()
     col_name.pop()
     col_name.insert(0, 'Season')
     r_df = r_df[col_name]
     roster_df = pd.concat([roster_df, r_df])
roster_df.drop(columns=['season'], inplace=True)
print(roster_df.shape)
roster_df.head()

(30970, 25)

,Season,team,position,depth_chart_position,jersey_number,status,full_name,first_name,last_name,birth_date,...,espn_id,yahoo_id,rotowire_id,pff_id,pfr_id,headshot_url,fantasy_data_id,sleeper_id,years_exp,sportradar_id
0,2013,ARI,C,NaN,72.0,CUT,Kyle Quinn,Kyle,Quinn,1990-02-09,...,NaN,NaN,NaN,8566.0,NaN,http://static.nfl.com/static/content/public/st...,NaN,NaN,NaN,NaN
1,2013,ARI,C,NaN,63.0,ACT,Lyle Sendlein,Lyle,Sendlein,1984-03-16,...,NaN,NaN,NaN,4062.0,SendLy20,http://static.nfl.com/static/content/public/st...,NaN,NaN,NaN,NaN
2,2013,ARI,C,NaN,68.0,CUT,Adam Bice,Adam,Bice,1989-06-30,...,NaN,NaN,NaN,8041.0,NaN,http://static.nfl.com/static/content/public/st...,NaN,NaN,NaN,NaN
3,2013,ARI,C,NaN,NaN,RSN,Philip Blake,Philip,Blake,1985-11-27,...,NaN,NaN,NaN,7108.0,BlakPh00,http://static.nfl.com/static/content/public/st...,NaN,NaN,NaN,NaN
4,2013,ARI,C,NaN,67.0,CUT,Deveric Gallington,Deveric,Gallington,1990-05-06,...,NaN,NaN,NaN,8563.0,NaN,http://static.nfl.com/static/content/public/st...,NaN,NaN,NaN,NaN

In [17]:
# Load snapcount data for seasons of 2013-2021 inclusive from scraped csv file.

snapcount_df = pd.read_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/snapcount_compiled_2013_2021.csv')
snapcount_df.drop(columns=['Unnamed: 0'], inplace=True)
print(snapcount_df.shape)
snapcount_df.head()

(4544, 14)

,Season,Pos,Team,Name,G,Snaps,TeamSnaps,Snap%,Per Game,RushPerc,TargetP,TouchPerc,FP,FPPerSnap
0,2013,WR,DEN,Demaryius Thomas,16,1106,1207.0,91.63,69.13,0.0,12.84,12.84,227.0,0.21
1,2013,WR,BAL,Torrey Smith,16,1098,1136.0,96.65,68.63,0.0,12.48,12.48,138.8,0.13
2,2013,WR,GB,Jordy Nelson,16,1083,1122.0,96.52,67.69,0.0,11.73,11.73,179.4,0.17
3,2013,WR,CIN,AJ Green,16,1055,1132.0,93.20,65.94,0.0,16.87,16.87,208.6,0.20
4,2013,WR,DEN,Eric Decker,16,1050,1207.0,86.99,65.63,0.0,12.95,12.95,192.8,0.18

In [18]:
# As today's focus is on WR, we will be looking at air yards via play by play data from nflfastr (https://github.com/nflverse/nflfastR).
# Such data will be used to calculate the total amount of air yards per season per player. 

pbp_df = pd.DataFrame()
y1 = 2013
y2 = 2021

for year in range(y1, y2+1):
    yearly_pbp_df = nfl.load_pbp_data(year)

    yearly_pbp_df = yearly_pbp_df.loc[yearly_pbp_df['pass_attempt'] == 1] # Because we want to look at air yards, we only look at plays where a pass was attempted
    # yearly_pbp_df = yearly_pbp_df.groupby('receiver_id', as_index=False)['air_yards'].sum()
    yearly_pbp_df = yearly_pbp_df.groupby(['receiver_id']).agg({'air_yards':'sum', 'yards_after_catch':'sum'}).reset_index()
    yearly_pbp_df['Season'] = year
    col_name = yearly_pbp_df.columns.tolist()
    col_name.pop()
    col_name.insert(0, 'Season')
    yearly_pbp_df = yearly_pbp_df[col_name]
    pbp_df = pd.concat([pbp_df, yearly_pbp_df])

print(pbp_df.shape)
pbp_df.head()

(4543, 4)

   Season receiver_id  air_yards  yards_after_catch
0    2013  00-0006101      964.0              224.0
1    2013  00-0015754      174.0               60.0
2    2013  00-0018956       -1.0               10.0
3    2013  00-0020337     1291.0              188.0
4    2013  00-0020494      641.0              182.0

In [43]:
print(list(pbp_df.columns))

['Season', 'air_yards', 'yards_after_catch']

In [20]:
def suffix_name_remove(full_name):
    return ' '.join(full_name.split()[0:2])

roster_wr_df = roster_df.loc[roster_df['position'] == 'WR', ['Season', 'full_name', 'gsis_id']]
roster_wr_df['full_name'] = roster_wr_df['full_name'].apply(suffix_name_remove)
count_dup_wr_df = roster_wr_df.groupby(['full_name', 'Season']).size() # groupby size() method allows to count number of unique values in a column in a given. 
count_dup_wr_df[count_dup_wr_df > 1]

full_name     Season
Chris Givens  2013      2
Chris Harper  2015      2
Joe Horn      2020      2
dtype: int64

In [22]:
# set snapcount and yearly to wr only; remove suffixes; rename player name column

yearly_wr_df = yearly_df.loc[yearly_df['Pos'] == 'WR']
snapcount_wr_df = snapcount_df.loc[snapcount_df['Pos'] == 'WR']

yearly_wr_df.loc[:,['Player']] = yearly_wr_df['Player'].apply(suffix_name_remove)
snapcount_wr_df.loc[:,['Name']] = snapcount_wr_df['Name'].apply(suffix_name_remove)


# yearly_wr_df['Player'] = yearly_wr_df['Player'].apply(suffix_name_remove) --- These two lines of code result in a SettingWithCopyWarning. This is because chained-indexing (making it difficult
# snapcount_wr_df['Name'] = snapcount_wr_df['Name'].apply(suffix_name_remove) - to tell whether a view or a copy is returned) has been detected but that does not mean the code ran incorrectly

snapcount_wr_df = snapcount_wr_df.rename({'Name':'Player'}, axis=1)
roster_wr_df = roster_wr_df.rename({'full_name':'Player'}, axis=1)

In [23]:
roster_wr_df = roster_wr_df.loc[roster_wr_df['Player'] != 'Chris Givens']
roster_wr_df = roster_wr_df.loc[roster_wr_df['Player'] != 'Chris Harper']
roster_wr_df = roster_wr_df.loc[roster_wr_df['Player'] != 'Joe Horn']
yearly_wr_df = yearly_wr_df.loc[yearly_wr_df['Player'] != 'Chris Givens']
yearly_wr_df = yearly_wr_df.loc[yearly_wr_df['Player'] != 'Chris Harper']
yearly_wr_df = yearly_wr_df.loc[yearly_wr_df['Player'] != 'Joe Horn']
snapcount_wr_df = snapcount_wr_df.loc[snapcount_wr_df['Player'] != 'Chris Givens']
snapcount_wr_df = snapcount_wr_df.loc[snapcount_wr_df['Player'] != 'Chris Harper']
snapcount_wr_df = snapcount_wr_df.loc[snapcount_wr_df['Player'] != 'Joe Horn']

In [24]:
roster_wr_df['Player'] = roster_wr_df['Player'].str.lower()
yearly_wr_df['Player'] = yearly_wr_df['Player'].str.lower()
snapcount_wr_df['Player'] = snapcount_wr_df['Player'].str.lower()

roster_wr_df['Player'] = roster_wr_df['Player'].str.replace('.','', regex=True)
yearly_wr_df['Player'] = yearly_wr_df['Player'].str.replace('.','', regex=True)
snapcount_wr_df['Player'] = snapcount_wr_df['Player'].str.replace('.','', regex=True)

At this point, we have compiled and largely cleaned up all the dataframes for consistency and ease in analysis. Now, we must find duplicate columns between snapcount and yearly stats data and drop the redudant columns. Then the roster, yearly stats, snapcount, and play by play dataframe will all be joined before analysis can be started.

In [25]:
list(set(snapcount_wr_df.columns.tolist()) & set(yearly_wr_df.columns.tolist()))

['G', 'Player', 'Season', 'Pos']

In [26]:
snapcount_wr_df = snapcount_wr_df.drop(['G', 'Pos'], axis=1)
yearly_wr_df = yearly_wr_df.drop(['Pos'], axis=1)

In [42]:
pbp_df.head()

             Season  air_yards  yards_after_catch
receiver_id
00-0006101     2013      964.0              224.0
00-0015754     2013      174.0               60.0
00-0018956     2013       -1.0               10.0
00-0020337     2013     1291.0              188.0
00-0020494     2013      641.0              182.0

In [27]:
wr_analysis_df = snapcount_wr_df.merge(
    yearly_wr_df, on=['Player', 'Season'], how='left'
)\
.merge(
    roster_wr_df, on=['Player','Season'], how='left'
)\
.merge(
    pbp_df.rename({'receiver_id':'gsis_id'}, axis =1)[['gsis_id','Season', 'air_yards', 'yards_after_catch']], on=['gsis_id', 'Season'], how='left'
)

wr_analysis_df.head()

,Season,Team,Player,Snaps,TeamSnaps,Snap%,Per Game,RushPerc,TargetP,TouchPerc,...,RushingAtt,ReceivingYds,ReceivingTD,FantasyPoints,Int,Fumbles,FumblesLost,gsis_id,air_yards,yards_after_catch
0,2013,DEN,demaryius thomas,1106,1207.0,91.63,69.13,0.0,12.84,12.84,...,0.0,1430.0,14.0,319.0,0.0,2.0,0.0,00-0027874,1753.0,827.0
1,2013,BAL,torrey smith,1098,1136.0,96.65,68.63,0.0,12.48,12.48,...,0.0,1128.0,4.0,201.8,0.0,1.0,0.0,00-0027996,2116.0,363.0
2,2013,GB,jordy nelson,1083,1122.0,96.52,67.69,0.0,11.73,11.73,...,0.0,1314.0,8.0,264.4,0.0,0.0,0.0,00-0026176,1466.0,424.0
3,2013,CIN,aj green,1055,1132.0,93.20,65.94,0.0,16.87,16.87,...,0.0,1426.0,11.0,306.6,0.0,1.0,0.0,00-0027942,2429.0,395.0
4,2013,DEN,eric decker,1050,1207.0,86.99,65.63,0.0,12.95,12.95,...,0.0,1288.0,11.0,279.8,0.0,2.0,1.0,00-0027690,1683.0,423.0

In [48]:
print(list(wr_analysis_df.columns))

print(wr_analysis_df.shape)

['Season', 'Team', 'Player', 'Snaps', 'TeamSnaps', 'Snap%', 'Per Game', 'RushPerc', 'TargetP', 'TouchPerc', 'FP', 'FPPerSnap', 'Tm', 'Age', 'G', 'GS', 'Tgt', 'Rec', 'PassingYds', 'PassingTD', 'PassingAtt', 'RushingYds', 'RushingTD', 'RushingAtt', 'ReceivingYds', 'ReceivingTD', 'FantasyPoints', 'Int', 'Fumbles', 'FumblesLost', 'gsis_id', 'air_yards', 'yards_after_catch']
(1954, 33)

In [28]:
wr_analysis_df = wr_analysis_df[[
    'Season', 'Team', 'Player', 'gsis_id', 'Snaps','TeamSnaps', 'G', 'Rec', 'ReceivingYds', 'ReceivingTD', 'Tgt', 'air_yards', 'TargetP', 'TouchPerc', 'yards_after_catch'
]]\
.rename({
    'Season':'season',
    'Team':'team',
    'Player':'player_name',
    'Snaps':'snaps',
    'TeamSnaps':'team_snaps',
    'G':'games_played',
    'Rec':'receptions',
    'ReceivingYds':'rec_yards',
    'ReceivingTD':'rec_tds',
    'Tgt':'targets',
    'TargetP':'target_share',
    'TouchPerc':'touch_perc'
}, axis=1)\
.assign(
    stand_fp = lambda x: x.rec_yards*0.1 + x.rec_tds*6
)\
.assign(
    ppr_fp = lambda x: x.stand_fp + x.receptions
)\
.assign(
    half_ppr_fp = lambda x: x.stand_fp + x.receptions*0.5  
)\
.assign(
    adot = lambda x: x.air_yards / x.targets
).dropna()

print(wr_analysis_df.shape)
wr_analysis_df.head(25)

(1720, 19)

,season,team,player_name,gsis_id,snaps,team_snaps,games_played,receptions,rec_yards,rec_tds,targets,air_yards,target_share,touch_perc,yards_after_catch,stand_fp,ppr_fp,half_ppr_fp,adot
0,2013,DEN,demaryius thomas,00-0027874,1106,1207.0,16.0,92.0,1430.0,14.0,142.0,1753.0,12.84,12.84,827.0,227.0,319.0,273.0,12.345070
1,2013,BAL,torrey smith,00-0027996,1098,1136.0,16.0,65.0,1128.0,4.0,137.0,2116.0,12.48,12.48,363.0,136.8,201.8,169.3,15.445255
2,2013,GB,jordy nelson,00-0026176,1083,1122.0,16.0,85.0,1314.0,8.0,127.0,1466.0,11.73,11.73,424.0,179.4,264.4,221.9,11.543307
3,2013,CIN,aj green,00-0027942,1055,1132.0,16.0,98.0,1426.0,11.0,178.0,2429.0,16.87,16.87,395.0,208.6,306.6,257.6,13.646067
4,2013,DEN,eric decker,00-0027690,1050,1207.0,16.0,87.0,1288.0,11.0,136.0,1683.0,12.95,12.95,423.0,194.8,281.8,238.3,12.375000
5,2013,NE,julian edelman,00-0027150,1021,1197.0,16.0,105.0,1056.0,6.0,151.0,1417.0,14.79,14.99,570.0,141.6,246.6,194.1,9.384106
6,2013,ARI,larry fitzgerald,00-0022921,998,1084.0,16.0,82.0,954.0,10.0,135.0,1363.0,13.53,13.73,335.0,155.4,237.4,196.4,10.096296
7,2013,HOU,deandre hopkins,00-0030564,995,1121.0,16.0,52.0,802.0,2.0,91.0,1221.0,9.15,9.15,181.0,92.2,144.2,118.2,13.417582
8,2013,HOU,andre johnson,00-0022044,994,1121.0,16.0,109.0,1407.0,5.0,181.0,2004.0,18.21,18.21,405.0,170.7,279.7,225.2,11.071823
9,2013,PHI,desean jackson,00-0026189,987,1103.0,16.0,82.0,1332.0,9.0,126.0,1742.0,12.77,13.07,497.0,187.2,269.2,228.2,13.825397
10,2013,CHI,brandon marshall,00-0024334,987,1057.0,16.0,100.0,1295.0,12.0,164.0,1986.0,16.62,16.62,283.0,201.5,301.5,251.5,12.109756
11,2013,PHI,riley cooper,00-0027758,980,1103.0,16.0,47.0,835.0,8.0,84.0,1300.0,8.47,8.47,241.0,131.5,178.5,155.0,15.476190
12,2013,WAS,pierre garcon,00-0026345,978,1144.0,16.0,113.0,1346.0,5.0,181.0,1651.0,18.61,18.81,661.0,164.6,277.6,221.1,9.121547
13,2013,TB,vincent jackson,00-0023496,969,1036.0,16.0,78.0,1224.0,7.0,160.0,2045.0,16.51,16.62,319.0,164.4,242.4,203.4,12.781250
14,2013,CHI,alshon jeffery,00-0029137,962,1057.0,16.0,89.0,1421.0,7.0,148.0,1867.0,15.49,17.15,415.0,184.1,273.1,228.6,12.614865
15,2013,PIT,antonio brown,00-0027793,955,1052.0,16.0,110.0,1499.0,8.0,167.0,1763.0,17.38,18.12,570.0,197.9,307.9,252.9,10.556886
16,2013,DET,kris durham,00-0028045,951,1135.0,16.0,38.0,490.0,2.0,85.0,983.0,8.94,8.94,123.0,61.0,99.0,80.0,11.564706
17,2013,MIA,mike wallace,00-0026901,951,1027.0,16.0,73.0,930.0,5.0,141.0,2215.0,14.83,15.14,273.0,123.0,196.0,159.5,15.709220
18,2013,SD,keenan allen,00-0030279,944,1057.0,15.0,71.0,1046.0,8.0,105.0,1217.0,11.02,11.02,449.0,152.6,223.6,188.1,11.590476
19,2013,CLE,greg little,00-0027997,940,1106.0,16.0,41.0,465.0,2.0,99.0,1126.0,10.53,10.53,190.0,58.5,99.5,79.0,11.373737
20,2013,DAL,dez bryant,00-0027902,933,997.0,16.0,93.0,1233.0,13.0,159.0,1849.0,17.04,17.15,524.0,201.3,294.3,247.8,11.628931
21,2013,ARI,michael floyd,00-0029638,930,1084.0,16.0,65.0,1041.0,5.0,113.0,1529.0,11.94,11.94,282.0,134.1,199.1,166.6,13.530973
22,2013,ATL,harry douglas,00-0026224,926,1077.0,16.0,85.0,1067.0,2.0,132.0,1107.0,14.25,14.25,514.0,118.7,203.7,161.2,8.386364
23,2013,SD,vincent brown,00-0028020,917,1110.0,16.0,41.0,472.0,1.0,70.0,852.0,7.52,7.52,84.0,53.2,94.2,73.7,12.171429
24,2013,BUF,robert woods,00-0030431,910,1027.0,14.0,40.0,587.0,3.0,85.0,1143.0,9.34,9.56,111.0,76.7,116.7,96.7,13.447059

In [52]:
# wr_analysis_df.to_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/wr_regression_analysis_2022.csv', index=False)
# index = True is default - by setting it to False, the row names (in this case the integer values) will not be saved

In [53]:
wr_analysis_df.corr()[['half_ppr_fp']]

                   half_ppr_fp
season               -0.010052
snaps                 0.899525
team_snaps            0.566294
games_played          0.549977
receptions            0.968032
rec_yards             0.988698
rec_tds               0.902693
targets               0.963934
air_yards             0.929996
target_share          0.307372
touch_perc            0.231348
yards_after_catch     0.902663
stand_fp              0.997776
ppr_fp                0.999030
half_ppr_fp           1.000000