In [1]:
import pandas as pd

In [3]:
pd.set_option('display.max_columns', None)

SNAPCOUNT_URL = 'https://raw.githubusercontent.com/fantasydatapros/data/master/snapcounts/{year}.csv'

start_year = 2013
end_year = 2021

snapcount_df = pd.DataFrame()

for year in range(start_year,end_year):
    yearly_sc_df = pd.read_csv(SNAPCOUNT_URL.format(year=year))
    yearly_sc_df['Season'] = year
    col_names = yearly_sc_df.columns.tolist()
    col_names.pop() #removes the last column name - 'Season'
    col_names.insert(0, 'Season')
    yearly_sc_df = yearly_sc_df[col_names]
    snapcount_df = pd.concat([snapcount_df, yearly_sc_df])

print(snapcount_df.shape)
snapcount_df.head()

(4152, 14)

,Season,Pos,Team,Name,G,Snaps,TeamSnaps,Snap%,Per Game,RushPerc,TargetP,TouchPerc,FP,FPPerSnap
0,2013,WR,DEN,Demaryius Thomas,16,1106,1207,91.63,69.13,0.0,12.84,12.84,227.0,0.21
1,2013,WR,BAL,Torrey Smith,16,1098,1136,96.65,68.63,0.0,12.48,12.48,138.8,0.13
2,2013,WR,GB,Jordy Nelson,16,1083,1122,96.52,67.69,0.0,11.73,11.73,179.4,0.17
3,2013,WR,CIN,AJ Green,16,1055,1132,93.20,65.94,0.0,16.87,16.87,208.6,0.20
4,2013,WR,DEN,Eric Decker,16,1050,1207,86.99,65.63,0.0,12.95,12.95,192.8,0.18

In [5]:
sc_2021_df = pd.read_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/snapcount_fp_2021.csv')
sc_2021_df['Season'] = 2021
sc_2021_df['Per Game'] = (sc_2021_df['Snaps']/sc_2021_df['G'])
sc_2021_df = sc_2021_df[col_names]

print(sc_2021_df.shape)
sc_2021_df.head()

(392, 14)

,Season,Pos,Team,Name,G,Snaps,TeamSnaps,Snap%,Per Game,RushPerc,TargetP,TouchPerc,FP,FPPerSnap
0,2021,QB,GB,Aaron Rodgers,16,983,1056.989247,93,61.437500,3,0,57,336.3,0.342116
1,2021,QB,PIT,Ben Roethlisberger,16,1076,1086.868687,99,67.250000,2,0,58,228.0,0.211896
2,2021,QB,NYJ,Joe Flacco,2,66,137.500000,48,33.000000,3,0,67,23.8,0.360606
3,2021,QB,BAL,Josh Johnson,4,128,284.444444,45,32.000000,7,0,73,48.4,0.378125
4,2021,QB,ATL,Matt Ryan,17,1023,1054.639175,97,60.176471,4,0,59,234.8,0.229521

In [6]:
snapcount_df = pd.concat([snapcount_df, sc_2021_df])
print(snapcount_df.shape)
snapcount_df.head()

(4544, 14)

,Season,Pos,Team,Name,G,Snaps,TeamSnaps,Snap%,Per Game,RushPerc,TargetP,TouchPerc,FP,FPPerSnap
0,2013,WR,DEN,Demaryius Thomas,16,1106,1207.0,91.63,69.13,0.0,12.84,12.84,227.0,0.21
1,2013,WR,BAL,Torrey Smith,16,1098,1136.0,96.65,68.63,0.0,12.48,12.48,138.8,0.13
2,2013,WR,GB,Jordy Nelson,16,1083,1122.0,96.52,67.69,0.0,11.73,11.73,179.4,0.17
3,2013,WR,CIN,AJ Green,16,1055,1132.0,93.20,65.94,0.0,16.87,16.87,208.6,0.20
4,2013,WR,DEN,Eric Decker,16,1050,1207.0,86.99,65.63,0.0,12.95,12.95,192.8,0.18

In [7]:
snapcount_df.to_csv('/Users/brandynklee/Python_Projects/fantasy_footballl_22/data/snapcount_2013_2021.csv')